local builtin = require("telescope.builtin")

vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find Files" })
vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "Search Git Files" })
vim.keymap.set("n", "<leader>fl", builtin.live_grep, { desc = "Grep Search" })
vim.keymap.set("n", "<leader>fw", function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Live Grep Search" })
vim.keymap.set("n", "<leader>fh", function()
    builtin.find_files({ find_command = { "rg", "--files", "--hidden", "--glob", "!**/.git/*" } })
end, { desc = "Search Hidden Files" })
